### ISSUE TITLE
ARCHIVENAME option does not preserve base path in name

### ISSUE THREAD

**Issue by ewrayjohnson** [BaseXdb/basex-contrib#2]
When using the ARCHIVENAME option, the base path is not stored in the items name.
For example, when processing a folder 'root', and a file exists 'root/basepath/archive.zip/data.xml', the item will have the name 'archive.zip/data.xml' instead of the expected 'basepath/archive.zip/data.xml'.
Here is the code used on WIndows:
db:add('mydb', 'C:/root', '', map { 'parser': 'xml', 'createfilter': '*.xml', 'addarchives': true(), 'archivename': true(), 'skipcorrupt' : true()  })

**Comment by ChristianGruen** [comment]
I slightly changed the title of this issue and created an entry in our issue tracker.

**Comment by ChristianGruen** [comment]
…closed (because it has been moved to the BaseX issue tracker).

**Comment by ChristianGruen** [comment]
…and fixed.
