### ISSUE TITLE
Adding JSON files results in files not retrievable via http client

### ISSUE THREAD

**Issue by ewrayjohnson** [BaseXdb/basex-contrib#3]
Using the following command:

db:add($database, $path,  '', map { 'parser': 'json', 'createfilter': '*.json', 'addarchives': true(), 'archivename': true(), 'skipcorrupt' : true() })

will add the json files in $path and subfolders and can be found via XQuery, but not retrievable using the path in the http client

When creating a new database and loading it with the same JSON files in the same path, the JSON files ARE retrievable using the path in the http client

**Comment by ChristianGruen** [comment]
I’m not sure how to reproduce this. Does it only happen with JSON files? Is it only the case when JSON files are in an archive?… Could you possibly provide us with a little self-contained example?

**Comment by ewrayjohnson** [comment]
I cannot reproduce it.  Now it is working as expected.  Here is what I did.

Step 1:
return db:add('mydatabase', 'c:/myroot',  '', map { 'parser': 'xml', 'createfilter': '*.xml', 'addarchives': true(), 'archivename': true(), 'skipcorrupt' : true() })

Step 2:
return db:add('mydatabase', 'c:/myroot',  '', map { 'parser': 'json', 'createfilter': '*.json', 'addarchives': true(), 'archivename': true(), 'skipcorrupt' : true() })

Step 3:
Using the GUI, the following worked fine and I could see the expected XML for both (the JSON as XML):
return db:open('mydatabase', 'samples/config.xml')
return db:open('mydatabase', 'examples/colors.json')
 
Step 4:
Using the http client, the http://localhost:8984/rest/mydatabase/ resulted in the following entries:
.....
<rest:resource type="xml" content-type="application/xml" size="610">samples/config.xml</rest:resource>
<rest:resource type="xml" content-type="application/xml" size="232">examples/colors.json</rest:resource>
....

Step 5:
Using the http client, http://localhost:8984/rest/mydatabase/samples/config.xml resulted in :
the expected XML content

Step 6:
Using the http client, http://localhost:8984/rest/mydatabase/examples/colors.json resulted in :
<rest:database name="mydatabase" resources="0"/>

**Comment by ChristianGruen** [comment]
Even better… I haven’t experienced the problem before, so I’ve closed the issue. Feel free to reopen it if it happens again.
