### ISSUE TITLE
Cant add raw files explicitly or text index ms word docs

### ISSUE THREAD

**Issue by ewrayjohnson** [BaseXdb/basex-contrib#4]
Here is what I want to do:  For a given folder and all its subfolders on my physical dive, mirror its contents including the contents of archives, parsing xml, json,html, text, etc. using their respective parser skipping invalids, and adding all other files as raw.  However I want the text inside archive files like docx to be indexed.

Note:  It would be nice if there was a single db:add method that allowed me to specify a map of filters to parsers with options, where all files that do not match a filter (or are invalid) will be optionally added as raw.

**Comment by ChristianGruen** [comment]
Noted. Please note that feature requests are usually discussed on our [basex-talk mailing list](http://basex.org/open-source/), so you might get more feedback over there.
